endOfLine: auto
singleQuote: true
jsxSingleQuote: true
quoteProps: as-needed
useTabs: false
trailingComma: none
tabWidth: 2
semi: false
printWidth: 120
bracketSpacing: true
bracketSameLine: false
arrowParens: always
